define({
	addUrlChartSource: "添加URL图表源",
	addLayerChartSource: "添加图层图表源",
	sourceLabel: "源标签",
	categoryField: "显示字段",
	actions: "操作",
	hightLightColor: "高亮颜色",
	urlChartSource: "URL图表源",
	layerChartSource:"图层图表源",
	searchUrl: "搜索URL",
	browse: "浏览",
	layers: "图层",
	availableFields: "可获取字段",
	charts: "图表",
	chartField: "图表字段",
	description: "描述",
	title: "标题",
	type: "类型",
	cancel: "取消",
	addChartSource: "添加图表源",
	updateChartSource: "更新图表源",
	chartSources:"图表源",
	chartSource:"图表源",
	general:"常规"
});